# Generated by Django 4.0.1 on 2022-01-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OperatorId', models.IntegerField(auto_created=True)),
                ('OperatorName', models.CharField(max_length=100)),
                ('OperatorCode', models.CharField(max_length=100)),
            ],
        ),
    ]
