# Generated by Django 4.0.1 on 2022-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManagerId', models.IntegerField(auto_created=True)),
                ('ManagerName', models.CharField(max_length=100)),
                ('ManagerPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
